# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\button.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog: QtWidgets.QMainWindow):
        Dialog.setObjectName("Dialog")
        Dialog.setGeometry(550, 0, 810, 80)
        Dialog.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.click = QtWidgets.QPushButton(Dialog)
        self.click.setGeometry(QtCore.QRect(5, 5, 260, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.click.setFont(font)
        self.click.setObjectName("click")
        self.doubleclick = QtWidgets.QPushButton(Dialog)
        self.doubleclick.setGeometry(QtCore.QRect(275, 5, 260, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.doubleclick.setFont(font)
        self.doubleclick.setObjectName("doubleclick")
        self.move = QtWidgets.QPushButton(Dialog)
        self.move.setGeometry(QtCore.QRect(545, 5, 260, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.move.setFont(font)
        self.move.setObjectName("move")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.click.setText(_translate("Dialog", "click"))
        self.doubleclick.setText(_translate("Dialog", "double click"))
        self.move.setText(_translate("Dialog", "move"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
